#!/bin/sh
# ztools
#Append to a file.

##################################################33


####################################################################
# A pile of global variables, please edit them according to your purpose
####################################################################

cmdname="zdown";
version="2012 alpha"
#formula: cmdname options values parameters
formula="$cmdname [option] filename";
func="A wrapper for scp actually to specifically download from 192.168.130.130 /home/limz/scppub"
# Option names
options="r v h";
loptions="recursive version help"
# Option value names. 0 for a no-value option.
values="0 0 0";
# Enable no-option mode when nonop=1, when it is legal for zero option
nonop=1;
# Number of parameters taken 
# minpara <= number of parameters <= maxpara
minpara=0;
maxpara=1;


#item separator symbol
isep="@zitem@"
#line separator symbol, to require a newline when printing
lsep="@zline@"

# Option explanations. Separate each other with ${isep} sign.
# Within each explanation content, use ${lsep} sign when ever you want to 
# start a new line when printing.
# A pair of doubly written signs results into a string with no special meaning
# For instance, "${lsep}${lsep}" prints just one "${lsep}" instead of "\n"
optexpl="pass -r option to scp\
@zitem@Print version info\
@zitem@Print help info"

# Notice:options, values and optexpl must contain the same number of items.

#Action when no argument is given
# Need redefination.
defaultop()
{
    scp -r limz@192.168.130.130:~/scppub/* .
    exit 0
}


. libzutil.sh

####################################################################
#Procedure design. Unreusable part.
####################################################################
clean_up()
{
    rm -f ${nametruck}.aux
    rm -f ${nametruck}.log
}



####################################################################
#Here we start our main program
####################################################################


if [ $on_h -eq 1 ];then
    zusage
fi

if [ $on_v -eq 1 ];then
    zversion
fi

if [ $parac -eq 1 ]; then
    if [ $on_r -eq 1 ];then 
	scp -r limz@192.168.130.130:~/scppub/$para1 .
    else
	scp limz@192.168.130.130:~/scppub/$para1 .
    fi
fi



