#!/bin/sh
# ztools
# Search and kill processes by a keyword.


####################################################################
# Definitions
####################################################################

cmdname="zkill"
version="2012 alpha"
#formula: cmdname options values parameters
formula="$cmdname [options] [keyword]";
func="Search and kill processes by a keyword.";
# Option names
options="f l h v";
# Long option names
loptions="force list help version"
# Option value names. 0 for a no-value option.
values="0 0 0 0";
# Enable no-option mode when nonop=1, when it is legal for zero option
nonop=1;
# Number of parameters taken 
# minpara <= number of parameters <= maxpara
minpara=0;
maxpara=1;


#item separator symbol
isep="@zitem@"
#line separator symbol, to require a newline when printing
lsep="@zline@"

# Option explanations. Separate each other with ${isep} sign.
# Within each explanation content, use ${lsep} sign when ever you want to 
# start a new line when printing.
# A pair of doubly written signs results into a string with no special meaning
# For instance, "${lsep}${lsep}" prints just one "${lsep}" instead of "\n"
optexpl="Kill without ask for confirmation\
@zitem@Just print kill list without actually killing\
@zitem@Print help info\
@zitem@Print version info";
# Notice:options, values and optexpl must contain the same number of items.

#Action when no argument is given
# Need redefination.

#octeon_root=/media/D/OCTEON-SDK/ 
octeon_root=/media/limz/Hlp/OCTEON-SDK2/

defaultop()
{
    pushd $octeon_root 
    . env-setup OCTEON_CN58XX
    popd
}


# Add this line to parse arguments
. libzutil.sh

####################################################################
#Procedure design
####################################################################

just_help()
{
    if [ "$formula" != "" ]
    then
	echo "Usage: $formula"
    fi

    echo "Function: $func"

    if [ $optc -gt 0 ]
    then
	echo Options:;
    fi

    ii=1;
    while [ ${ii} -le ${optc} ]
    do
	getop ${ii}
	getva ${ii}
	getlongop $ii
	op="-$op"
	longop="--$longop"
	printf "\t%-6s%-20s%-10s"	"${op}" "${longop}" "${va}" 
	prtoel ${ii}
	ii=$((${ii}+1))
    done

    if [ "$version" != "" ]
    then
	echo "Version: $version"
    fi

    if [ "$notice" != "" ]
    then
	echo "Notice: $notice"
    fi

    if [ "$dependlist" != "" ]
    then
	echo "Depend softwares: $dependlist"
    fi
}


if [ $on_h -eq 1 ];then
    just_help
elif [ $on_v -eq 1 ];then
    echo "Version : $version"
elif [ "$1" != "" ];then
    defaultop
fi







