#!/bin/bash
# ztools

####################################################################
# A pile of global variables, please edit them according to your purpose
####################################################################

cmdname="zsysarch";
version="2012 alpha"
#formula: cmdname options values parameters
formula="$cmdname options";
func="A software development accelerator to create a helloworld source code with a makefile";
# Option names
options="b r p f v h";
loptions="back restore partition tarfile version help"
# Option value names. 0 for a no-value option.
values="0 0 pname tarname 0 0";
# Enable no-option mode when nonop=1, when it is legal for zero option
nonop=0;
# Number of parameters taken 
# minpara <= number of parameters <= maxpara
minpara=0;
maxpara=0;


#item separator symbol
isep="@zitem@"
#line separator symbol, to require a newline when printing
lsep="@zline@"

# Option explanations. Separate each other with ${isep} sign.
# Within each explanation content, use ${lsep} sign when ever you want to 
# start a new line when printing.
# A pair of doubly written signs results into a string with no special meaning
# For instance, "${lsep}${lsep}" prints just one "${lsep}" instead of "\n"
optexpl="Backup\
@zitem@Restore\
@zitem@Partition to backup or restore\
@zitem@Tar filename to create or depress from\
@zitem@Print version info\
@zitem@Print help info";
# Notice:options, values and optexpl must contain the same number of items.

#Action when no argument is given
# Need redefination.
defaultop()
{
	exit 1;
}


. libzutil.sh

####################################################################
#Procedure design. Unreusable part.
####################################################################


if [ $on_h -eq 1 ]
then
	zusage;
fi

if [ $on_v -eq 1 ]
then
	zversion
fi


if [ $on_b -eq 1 ]
then
	tar jcvfp /media/E/"$value_f".tar.bz2 "$value_p" --exclude="$value_p"/proc --exclude="$value_p"/lost+found --exclude="$value_p"/mnt --exclude="$value_p"/sys --exclude="$value_p"/windows --exclude="$value_p"/media --exclude="$value_p"/tmp --exclude="$value_p"/run --exclude="$value_p"/var

fi


if [ $on_r -eq 1 ]
then

	tar jxvfp /media/E/"$value_f".tar.bz2 -C "$value_p"
	cd $value_p && mkdir proc lost+found mnt sys media windows tmp
fi





